### ISSUE TITLE
Missing content-type header when craeting new folder with dummy file

### ISSUE THREAD

**Issue by timbl** [solid/folder-pane#18]
Client side error:
`Error: Web error: 400 (Bad Request) on PUT of <https://timbl.com/timbl/Office/2021/.dummy>`

Server side says request is missing a content-type header

**Comment by angelo-v** [comment]
Are you running the latest mashlib on timbl.com? I think this should be fixed already

**Comment by angelo-v** [comment]
Ah ok, you said it on the chat already, so I will close this
